Repository pvgcoetecell/websitev2, pull requests merged in 2022-10, with the labels that each got.

#9 removed images
  Mrunal patil.jpg
  riyakarambelkaredc1.jpg
Labels: fix

#10 removied socials
  Documentationteam.html
Labels: fix

#16 removed profile
  coreteam.html
Labels: enhancement

#18 useless images removed
  Gallery.html
  RahulPatiledc1.jpg
Labels: Optimization

#19 Removed member
  TechnicalTeam.html
Labels: fix

#20 udate
  Curationteam.html
  Tejas Kulkarni.jpg
  contact.html
Labels: fix

#23 Added new files
  newfile.html
  newfile3.html
Labels: documentation

#24 added 4 files
  newfile4.html
  newfile5.html
Labels: documentation, enhancement, fix, Optimization

#25 added prr
  newfile5.html
  newfile6.html
Labels: fix

#26 added more code
  newfile6.html
Labels: enhancement

#27 added home
  homer.html
Labels: enhancement

#36 Fix Issue #35 Improving folder structure and updating links
  Curationteam.html
  Documentationteam.html
  Gallery.html
  Teams.css
  coreteam.html
  css/Gallery.css
  css/Teams.css
  css/home.css
  home.css
  homer.html
  images/Aishwarya Patiledc.jpg
  images/Akansha Mahankar bg edited.jpg
  images/Akshat Jain.jpg
  images/AnshukaJainedc .jpg
  images/Anurag SE.jpg
  images/Anushka Kulkarni.jpg
  images/Anushray Pinghale.jpg
  images/Atharva Gandhe.jpg
  images/Bhakti Pande.jpg
  images/Chaitanya Giramedc.jpg
  images/Divya Badge edc...jpg
  images/EDC_SHREEKAR .jpg
  images/GauravBurandeedc-1(1).jpg
  images/Jayesh Suryawanshi.jpg
  images/Mitesh Kulkarniedc.jpg
  images/Pritam patil.jpg
  images/Prithviraj Patiledc.jpg
  images/RajaseeThakareedc-1.jpg
  images/Ritinedc-1.jpg
  images/Ruchita Kagne.jpg
  images/Rutvij Deoedc.jpg
  images/SamruddhiPatil.jpg
  images/Shambhavi.jpg
  images/Sharvari Karhe.jpg
  images/Sharvinpharande.jpg
  images/Shivani Kulkarni.jpg
  images/Shreeyash Bhavsaredc.jpg
  images/Shreyash Paralkaredc.jpg
  images/ShrutiKulkarniedc-1.jpg
  images/Shrutika.jpg
  images/Tanvi Mokashi.jpg
  images/Tejas Kulkarni.jpg
  images/Vedant Umbrajkar.jpg
  images/githublogo.jpg
  images/linkdinlogo21.jpg
  images/logo.png
  images/prajwalmahanwar.jpg
Labels: hacktoberfest-accepted, approved

#40 Fix Issue #39 Remove unwanted html tags and add new design for social media logos
  css/home.css
  homer.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 Update Gallery.html
  Gallery.html
Labels: hacktoberfest, hacktoberfest-accepted, approved
